### ISSUE TITLE
Cannot find the object "dbo.instance_details"

### ISSUE THREAD

**Issue by JJAulakh** [imajaydwivedi/SQLMonitor#233]
**Describe the bug**
Hi Team,

I am getting the below error while installing SQL monitor on SQL 2022 Dev edition.

**Screenshots**
2023Jan13_1505 INFO:      *****Working on step '2__AllDatabaseObjects'..
2023Jan13_1505 INFO:      Creating All Objects in [zDBA] database..
2023Jan13_1505 INFO:      MultiServerViews are considered for upgrade.
2023Jan13_1505 INFO:      Runtime All Server Objects file code is generated.
2023Jan13_1505 INFO:      $AllDatabaseObjectsFilePath = 'E:\GitHub\SQLMonitor\DDLs\SCH-Create-All-Objects-RuntimeUsedFile.sql'
2023Jan13_1505 INFO:      Remove temp file 'E:\GitHub\SQLMonitor\DDLs\SCH-Create-All-Objects-RuntimeUsedFile.sql'..
2023Jan13_1505 INFO:      Update objects on Inventory Server..
Cannot find the object "dbo.instance_details" because it does not exist or you do not have permissions.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.143\allcommands.ps1:149032 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (V3DVDBSQL01:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Invoke-DbaQuery

**Comment by imajaydwivedi** [comment]
Hi @JJAulakh, This is not an issue with SQLMonitor.

You are supposed to baseline your Inventory Server first before you can baseline any other SQLInstance.
Above error suggests that your Inventory Server is not baselined properly or details of Inventory Server+Database in Wrapper script are incorrect.

For general support, join `#sqlmonitor` channel on [sqlcommunity.slack.com](https://ajaydwivedi.com/go/slack) workspace.
