### ISSUE TITLE
db query error: mssql: Invalid column name 'value'.

### ISSUE THREAD

**Issue by JJAulakh** [imajaydwivedi/SQLMonitor#240]
**Describe the bug**
I am getting the below errors in the grafana live distributed dashboard. I haven't uploaded the other dashboard yet. Please suggest if I did any mistake in installation step.

Inspect: OS Processes @ db query error: mssql: Invalid column name 'host_name'.
Inspect: CPU - @ db query error: mssql: Invalid column name 'value'.
Inspect: Memory Grants Pending- @ db query error: mssql: Invalid column name 'value'.
db query error: mssql: Invalid column name 'collection_time_utc'.

**Screenshots**
Screenshot attached
![SQLMonitor](https://user-images.githubusercontent.com/122651131/217963372-03cd650b-abb2-44ea-bb1e-db0f225384ab.png)

I am using SQL 2022 dev edition as a baseline server. Both baseline and monitoring servers are the same machine.

**Comment by imajaydwivedi** [comment]
Kindly follow the video tutorials.

For help, kindly join **#sqlmonitor** channel on [SQLCommunity Slack](https://ajaydwivedi.com/go/slack)

**Comment by JJAulakh** [comment]
Thanks Ajay. I have joined the slack channel and will reinstall this tool again with the same steps as suggested in your video. Once again, Thanks.
