### ISSUE TITLE
be able to specify port and set connection string parameters on the wrapper

### ISSUE THREAD

**Issue by scervino-inmar** [imajaydwivedi/SQLMonitor#245]
**Is your feature request related to a problem? Please describe.**

Yes
1- In our sql server we do not use the default port, so all the invoke-dbaquery or any module that tries to connect to the database fails
2- also even with having the port configured Im getting the following error,
"The certificate chain was issued by an authority that is not trusted"
3- also I was getting error on the policy command, not sure if this is something that we can ignore or not,
  
Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Unrestricted -Force
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of
RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:5
     Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Unrestri ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
     FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand

**Describe the solution you'd like**
1- be able to specify the port on the wrapper
2- be able to set Trust Server Certificate= True as a workaround in the wrapper
3- Im not sure what is needed here

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by imajaydwivedi** [comment]
Support for SQLInstances that connect only after specifying Port No is added.

SQLInstance names have to be passed like usual in Wrapper -
![image](https://user-images.githubusercontent.com/18259277/223004235-836b9d4b-e839-4a55-8676-dd6d4566ad7f.png)

After SQLMonitor installation, the `sql_instance` & `port_no` would appear in different columns in `dbo.instance_details` table.
![image](https://user-images.githubusercontent.com/18259277/223003194-0107ae44-b910-44e9-8ac5-1bea988dc1de.png)

On SQLMonitor grafana dashboards, the SQLInstance appears without PortNo.
![image](https://user-images.githubusercontent.com/18259277/223004765-34c77fcc-f72b-4c61-a5b9-c99347db5ae4.png)
