### ISSUE TITLE
We are getting the below error how to fixed this 

### ISSUE THREAD

**Issue by vslknsgr** [imajaydwivedi/SQLMonitor#27]
2024Feb16_1042 ERROR:     Seems either [DBA] does not exists, or the data/log files are present in C:\ drive. 
	 Kindly rectify this issue.
F:\GitHub\SQLMonitor\SQLMonitor\Install-SQLMonitor.ps1 : Stop here. Fix above issue.
At F:\Github\SQLMonitor\Private\Wrapper-InstallSQLMonitor.ps1:75 char:1
+ F:\GitHub\SQLMonitor\SQLMonitor\Install-SQLMonitor.ps1 @Params

**Comment by vslknsgr** [comment]
Now this fixed

**Comment by Bore-alis** [comment]
How did you fix it?

**Comment by imajaydwivedi** [comment]
@Bore-alis The issue is same as mentioned in error message.

Either the DBA database exists in C:\ drive somewhere, or it does not exist.

If you wish to skip this DBA database drive check, kindly use `SkipDriveCheck` parameter with `true` value
