### ISSUE TITLE
We are getting error on two step 3__XEventSession and 9__CopyDbaToolsModule2Host

### ISSUE THREAD

**Issue by vslknsgr** [imajaydwivedi/SQLMonitor#28]
**2024Feb16_1240 INFO:      *****Working on step '3__XEventSession'..**
2024Feb16_1240 INFO:      $XEventSessionFilePath = 'D:\GitHub\SQLMonitor\DDLs\SCH-Create-XEvents.sql'
2024Feb16_1240 INFO:      Computed XEvent files directory -> 'D:\MSSQL15.MSSQLSERVER\XEvents'..
2024Feb16_1240 INFO:      Create XEvent session named [xevent_metrics]..

The target, "5B2DA06D-898A-43C8-9309-39BBBE93EBBD.package0.event_file", encountered a configuration error during initialization. 
Object cannot be added to the event session. The operating system returned error 5: 'Access is denied.
' while creating the file 'C:\Program Files\Microsoft SQL 
Server\MSSQL15.SQL2019\MSSQL\xevents\xevent_metrics_0_133525896392450000.xel'.
At line:97864 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SQLMASTER\SQL2019:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Invoke-DbaQuery

----------------------------------------------------------------------------------------------------------------------------------------------

2024Feb16_1243 INFO:      *********Working on step '9__CopyDbaToolsModule2Host'..****
2024Feb16_1243 INFO:      $DbaToolsFolderPath = 'D:\Github\dbatools'
2024Feb16_1243 INFO:      $dbaToolsLibraryFolderPath = 'D:\Github\dbatools.library'
Import-LocalizedData : Cannot find the Windows PowerShell data file 'dbatools.psd1' in directory 
'D:\GitHub\SQLMonitor\SQLMonitor\en-US\', or in any parent culture directories.
At D:\GitHub\SQLMonitor\SQLMonitor\Install-SQLMonitor.ps1:1937 char:5
+     Import-LocalizedData -BaseDirectory $dbatoolsConfigFileDirectory  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\GitHub\SQLMo...S\dbatools.psd1:String) [Import-LocalizedData], PSInvalidOperationE 
   xception
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData

**Comment by imajaydwivedi** [comment]
Kindly utilize the commands provided in `\Wrapper-Samples\Wrapper-InstallSQLMonitor.ps1` to download the `dbatools` & `dbatools.library` modules.

![image](https://github.com/imajaydwivedi/SQLMonitor/assets/18259277/a5e9c483-76e8-4283-a096-6c877120d76a)

**Comment by imajaydwivedi** [comment]
Below error indicates SQLServerAgent service account does not have READ/WRITE permissions on the path where XEvent files are being created.

In this case, kindly utilize the parameter `XEventDirectory`, and place the XEvent files in a folder where SQLDatabase Engine & Agent have full permissions.

![image](https://github.com/imajaydwivedi/SQLMonitor/assets/18259277/e1c1e858-9ce0-4f10-8121-ecb9b1e0bb3e)


```
**2024Feb16_1240 INFO: ***Working on step '3__XEventSession'..
2024Feb16_1240 INFO: $XEventSessionFilePath = 'D:\GitHub\SQLMonitor\DDLs\SCH-Create-XEvents.sql'
2024Feb16_1240 INFO: Computed XEvent files directory -> 'D:\MSSQL15.MSSQLSERVER\XEvents'..
2024Feb16_1240 INFO: Create XEvent session named [xevent_metrics]..

The target, "5B2DA06D-898A-43C8-9309-39BBBE93EBBD.package0.event_file", encountered a configuration error during initialization.
Object cannot be added to the event session. The operating system returned error 5: 'Access is denied.
' while creating the file 'C:\Program Files\Microsoft SQL
Server\MSSQL15.SQL2019\MSSQL\xevents\xevent_metrics_0_133525896392450000.xel'.
At line:97864 char:9
```
